FIBER_DEPENDENT_PROPERTIES = {'node_diameter' 'paranode_diameter_1' ...
'paranode_diameter_2' 'axon_diameter' 'paranode_length_2' 'internode_length'
'stin_seg_length' 'number_lemella' 'rho_axial_i' 'rho_axial_1' 'rho_axial_2'...
'cm_i' 'cm_1' 'cm_2' 'g_1' 'g_2' 'g_i' 'g_pas_i' 'g_pas_1' 'g_pas_2' 'xraxial_node' ...
'xraxial_1' 'xraxial_2' 'xraxial_i' 'xg_1' 'xg_2' 'xg_i' 'xc_1' 'xc_2' ...
'xc_i'};

NON_FIBER_DEPENDENT_PROPERTIES = {'node_length' 'paranode_length_1' ...
'space_p1' 'space_p2' 'space_i' 'n_STIN' 'n_internodes' 'v_init' ...
'rho_periaxonal' 'rho_axial_node' 'cap_nodal' 'cap_internodal' 'cap_myelin'...
'g_myelin' 'xg_node' 'xc_node'
};

CURRENT_OFF_LIMIT_PROPERTIES = {'n_STIN' 'v_init'};

NON_PROPERTY_PROPS = {'parent' 'spatial_obj' 'props_up_to_date_in_NEURON'...
'NON_PROPERTY_PROPS' 'CURRENT_OFF_LIMIT_PROPERTIES' 'NON_FIBER_DEPENDENT_PROPERTIES' ...
'FIBER_DEPENDENT_PROPERTIES'};

%What if one changes the internode length? How should the other values be 
%updated?